
stages:
  - lint
  - build
  - deploy

variables:
  DEV_DEPLOY_DIR: '/var/host/www/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME'
  DEV_BACKEND_URL: https://boilerplate12345.kozhin.dev
#  PROD_DEPLOY_DIR: [prod deploy dir]
#  PROD_BACKEND_URL: [prod backend url]


# Lint stage

lint:
  stage: lint
  script:
    - yarn
    - yarn lint


# Build stage

.build_template:
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - public/
  script:
    - yarn install --production
    - yarn build
    - echo "$CI_COMMIT_REF_NAME-$CI_JOB_ID" > $CI_PROJECT_DIR/public/version.txt

build_dev:
  extends: .build_template
  environment: dev
  only:
    - master
  variables:
    APP_ENV: preview
    APP_BACKEND_URL: $DEV_BACKEND_URL

#build_prod:
#  extends: .build_template
#  environment: production
#  only:
#    - prod
#  variables:
#    APP_ENV: production
#    APP_BACKEND_URL: $PROD_BACKEND_URL


# Deploy stage

deploy_dev:
  stage: deploy
  environment: dev
  only:
    - master
  tags:
    - dev-server
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p $DEV_DEPLOY_DIR
    - rsync --recursive --remove-source-files --delete ./ $DEV_DEPLOY_DIR

#deploy_prod:
#  stage: deploy
#  environment: production
#  only:
#    - prod
#  tags:
#    - [prod runner tag]
#  variables:
#    GIT_STRATEGY: none
#    CURRENT_DIR: $PROD_DEPLOY_DIR/current
#    PREVIOUS_DIR: $PROD_DEPLOY_DIR/previous
#    DEPLOY_DIR: $PROD_DEPLOY_DIR/$CI_PIPELINE_ID
#  script:
#    - mkdir -p $DEPLOY_DIR
#    - rsync --recursive --remove-source-files --delete ./ $DEPLOY_DIR
#    - rm -rf $(readlink -f $PREVIOUS_DIR) $PREVIOUS_DIR
#    - if [ -d "$CURRENT_DIR" ]; then mv $CURRENT_DIR $PREVIOUS_DIR; fi
#    - ln -s $DEPLOY_DIR $CURRENT_DIR
